ble-face argument_error=fg={{colors.surface.dark.hex}},bg={{colors.error.dark.hex}}
ble-face argument_option=fg={{colors.primary.dark.hex}}
ble-face auto_complete=fg={{colors.surface_variant.dark.hex}}
ble-face cmdinfo_cd_cdpath=fg={{colors.primary.dark.hex}},bg={{colors.error.dark.hex}}
ble-face command_alias=fg={{colors.primary.dark.hex}}
ble-face command_builtin=fg={{colors.error.dark.hex}}
ble-face command_builtin_dot=fg={{colors.error.dark.hex}},bold
ble-face command_directory=fg={{colors.secondary.dark.hex}},underline
ble-face command_file=fg={{colors.tertiary_container.dark.hex}}
ble-face command_function=fg={{colors.primary_container.dark.hex}}
ble-face command_jobs=fg={{colors.error.dark.hex}},bold
ble-face command_keyword=fg={{colors.primary.dark.hex}}
ble-face command_suffix=fg={{colors.tertiary.dark.hex}},bg={{colors.secondary.dark.hex}}
ble-face command_suffix_new=fg={{colors.tertiary.dark.hex}},bg={{colors.error.dark.hex}}
ble-face disabled=fg={{colors.outline_variant.dark.hex}}
ble-face filename_block=fg={{colors.tertiary.dark.hex}},bg={{colors.surface.dark.hex}},underline
ble-face filename_character=fg={{colors.tertiary.dark.hex}},bg={{colors.surface.dark.hex}},underline
ble-face filename_directory=fg={{colors.secondary.dark.hex}},underline
ble-face filename_directory_sticky=fg={{colors.tertiary.dark.hex}},bg={{colors.primary.dark.hex}},underline
ble-face filename_executable=fg={{colors.tertiary_container.dark.hex}},underline
ble-face filename_link=fg={{colors.primary.dark.hex}},underline
ble-face filename_ls_colors=underline
ble-face filename_orphan=fg={{colors.surface.dark.hex}},bg={{colors.error.dark.hex}},underline
ble-face filename_other=underline
ble-face filename_pipe=fg={{colors.secondary.dark.hex}},bg={{colors.surface.dark.hex}},underline
ble-face filename_setgid=fg={{colors.surface.dark.hex}},bg={{colors.error_container.dark.hex}},underline
ble-face filename_setuid=fg={{colors.surface.dark.hex}},bg={{colors.primary_container.dark.hex}},underline
ble-face filename_socket=fg={{colors.primary.dark.hex}},bg={{colors.surface.dark.hex}},underline
ble-face filename_url=fg={{colors.primary.dark.hex}},underline
ble-face filename_warning=fg={{colors.error.dark.hex}},underline
ble-face menu_complete_match=bold
ble-face menu_complete_selected=reverse
ble-face menu_desc_default=none
ble-face menu_desc_quote=ref:syntax_quoted
ble-face menu_desc_type=ref:syntax_delimiter
ble-face menu_filter_fixed=bold
ble-face menu_filter_input=fg={{colors.surface.dark.hex}},bg={{colors.primary_container.dark.hex}}
ble-face overwrite_mode=fg={{colors.surface.dark.hex}},bg={{colors.secondary.dark.hex}}
ble-face prompt_status_line=fg={{colors.tertiary.dark.hex}},bg={{colors.outline_variant.dark.hex}}
ble-face region=fg={{colors.tertiary.dark.hex}},bg={{colors.error_container.dark.hex}}
ble-face region_insert=fg={{colors.tertiary_container.dark.hex}},bg={{colors.tertiary.dark.hex}}
ble-face region_match=fg={{colors.tertiary.dark.hex}},bg={{colors.error.dark.hex}}
ble-face region_target=fg={{colors.surface.dark.hex}},bg={{colors.error_container.dark.hex}}
ble-face syntax_brace=fg={{colors.secondary.dark.hex}},bold
ble-face syntax_command=fg={{colors.error_container.dark.hex}}
ble-face syntax_comment=fg={{colors.outline_variant.dark.hex}}
ble-face syntax_default=none
ble-face syntax_delimiter=bold
ble-face syntax_document=fg={{colors.primary_container.dark.hex}}
ble-face syntax_document_begin=fg={{colors.primary_container.dark.hex}},bold
ble-face syntax_error=fg={{colors.tertiary.dark.hex}},bg={{colors.error.dark.hex}}
ble-face syntax_escape=fg={{colors.primary.dark.hex}}
ble-face syntax_expr=fg={{colors.secondary.dark.hex}}
ble-face syntax_function_name=fg={{colors.primary_container.dark.hex}},bold
ble-face syntax_glob=fg={{colors.error_container.dark.hex}},bold
ble-face syntax_history_expansion=fg={{colors.tertiary.dark.hex}},bg={{colors.error.dark.hex}}
ble-face syntax_param_expansion=fg={{colors.secondary.dark.hex}}
ble-face syntax_quotation=fg={{colors.tertiary_container.dark.hex}},bold
ble-face syntax_quoted=fg={{colors.tertiary_container.dark.hex}}
ble-face syntax_tilde=fg={{colors.secondary.dark.hex}},bold
ble-face syntax_varname=fg={{colors.error_container.dark.hex}}
ble-face varname_array=fg={{colors.error_container.dark.hex}},bold
ble-face varname_empty=fg={{colors.primary_container.dark.hex}}
ble-face varname_export=fg={{colors.error.dark.hex}},bold
ble-face varname_expr=fg={{colors.primary_container.dark.hex}},bold
ble-face varname_hash=fg={{colors.primary_container.dark.hex}},bold
ble-face varname_new=fg={{colors.primary.dark.hex}}
ble-face varname_number=fg={{colors.error.dark.hex}}
ble-face varname_readonly=fg={{colors.error.dark.hex}}
ble-face varname_transform=fg={{colors.secondary.dark.hex}},bold
ble-face varname_unset=fg={{colors.outline_variant.dark.hex}}
ble-face vbell=none
ble-face vbell_erase=none
ble-face vbell_flash=fg={{colors.tertiary_container.dark.hex}},reverse
