-- Auto-generated by Matugen — do not edit directly.

local M = {}

-- Source color
M.source_color = "{{colors.source_color.default.hex}}"

-- Primary
M.primary = "{{colors.primary.default.hex}}"
M.on_primary = "{{colors.on_primary.default.hex}}"
M.primary_container = "{{colors.primary_container.default.hex}}"
M.on_primary_container = "{{colors.on_primary_container.default.hex}}"
M.primary_fixed = "{{colors.primary_fixed.default.hex}}"
M.primary_fixed_dim = "{{colors.primary_fixed_dim.default.hex}}"
M.on_primary_fixed = "{{colors.on_primary_fixed.default.hex}}"
M.on_primary_fixed_variant = "{{colors.on_primary_fixed_variant.default.hex}}"

-- Secondary
M.secondary = "{{colors.secondary.default.hex}}"
M.on_secondary = "{{colors.on_secondary.default.hex}}"
M.secondary_container = "{{colors.secondary_container.default.hex}}"
M.on_secondary_container = "{{colors.on_secondary_container.default.hex}}"
M.secondary_fixed = "{{colors.secondary_fixed.default.hex}}"
M.secondary_fixed_dim = "{{colors.secondary_fixed_dim.default.hex}}"
M.on_secondary_fixed = "{{colors.on_secondary_fixed.default.hex}}"
M.on_secondary_fixed_variant = "{{colors.on_secondary_fixed_variant.default.hex}}"

-- Tertiary
M.tertiary = "{{colors.tertiary.default.hex}}"
M.on_tertiary = "{{colors.on_tertiary.default.hex}}"
M.tertiary_container = "{{colors.tertiary_container.default.hex}}"
M.on_tertiary_container = "{{colors.on_tertiary_container.default.hex}}"
M.tertiary_fixed = "{{colors.tertiary_fixed.default.hex}}"
M.tertiary_fixed_dim = "{{colors.tertiary_fixed_dim.default.hex}}"
M.on_tertiary_fixed = "{{colors.on_tertiary_fixed.default.hex}}"
M.on_tertiary_fixed_variant = "{{colors.on_tertiary_fixed_variant.default.hex}}"

-- Error
M.error = "{{colors.error.default.hex}}"
M.on_error = "{{colors.on_error.default.hex}}"
M.error_container = "{{colors.error_container.default.hex}}"
M.on_error_container = "{{colors.on_error_container.default.hex}}"

-- Surface
M.surface = "{{colors.surface.default.hex}}"
M.on_surface = "{{colors.on_surface.default.hex}}"
M.surface_bright = "{{colors.surface_bright.default.hex}}"
M.surface_dim = "{{colors.surface_dim.default.hex}}"
M.surface_variant = "{{colors.surface_variant.default.hex}}"
M.on_surface_variant = "{{colors.on_surface_variant.default.hex}}"
M.surface_container = "{{colors.surface_container.default.hex}}"
M.surface_container_low = "{{colors.surface_container_low.default.hex}}"
M.surface_container_high = "{{colors.surface_container_high.default.hex}}"
M.surface_container_highest = "{{colors.surface_container_highest.default.hex}}"
M.surface_container_lowest = "{{colors.surface_container_lowest.default.hex}}"

-- Outline
M.outline = "{{colors.outline.default.hex}}"
M.outline_variant = "{{colors.outline_variant.default.hex}}"

-- Inverse
M.inverse_surface = "{{colors.inverse_surface.default.hex}}"
M.inverse_on_surface = "{{colors.inverse_on_surface.default.hex}}"
M.inverse_primary = "{{colors.inverse_primary.default.hex}}"

-- Background
M.background = "{{colors.background.default.hex}}"
M.on_background = "{{colors.on_background.default.hex}}"

-- Misc
M.scrim = "{{colors.scrim.default.hex}}"
M.shadow = "{{colors.shadow.default.hex}}"
M.surface_tint = "{{colors.surface_tint.default.hex}}"

return M
