# zsh-syntax-highlighting theme generated by matugen
# Material Design 3 colors mapped to ZSH_HIGHLIGHT_STYLES (valid keys only)

# Main syntax highlighting
ZSH_HIGHLIGHT_STYLES[default]='none'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg={{colors.error.dark.hex}},bold'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg={{colors.primary.dark.hex}},bold'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg={{colors.primary.dark.hex}}'
ZSH_HIGHLIGHT_STYLES[global-alias]='fg={{colors.primary.dark.hex}}'
ZSH_HIGHLIGHT_STYLES[precommand]='fg={{colors.tertiary.dark.hex}},bold'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg={{colors.error_container.dark.hex}}'
ZSH_HIGHLIGHT_STYLES[autodirectory]='fg={{colors.secondary.dark.hex}},underline,bold'
ZSH_HIGHLIGHT_STYLES[path]='fg={{colors.secondary.dark.hex}},underline'
ZSH_HIGHLIGHT_STYLES[path_pathseparator]='fg={{colors.secondary.dark.hex}}'
ZSH_HIGHLIGHT_STYLES[globbing]='fg={{colors.error_container.dark.hex}},bold'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg={{colors.tertiary.dark.hex}},bg={{colors.error.dark.hex}}'
ZSH_HIGHLIGHT_STYLES[command-substitution]='none'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter]='fg={{colors.primary.dark.hex}}'
ZSH_HIGHLIGHT_STYLES[process-substitution]='none'
ZSH_HIGHLIGHT_STYLES[process-substitution-delimiter]='fg={{colors.primary.dark.hex}}'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg={{colors.primary.dark.hex}}'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg={{colors.primary.dark.hex}}'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg={{colors.primary.dark.hex}}'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument-delimiter]='fg={{colors.primary.dark.hex}}'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg={{colors.tertiary_container.dark.hex}}'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg={{colors.tertiary_container.dark.hex}}'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg={{colors.tertiary_container.dark.hex}}'
ZSH_HIGHLIGHT_STYLES[rc-quote]='fg={{colors.tertiary_container.dark.hex}}'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg={{colors.tertiary_container.dark.hex}}'
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg={{colors.primary.dark.hex}}'
ZSH_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg={{colors.primary.dark.hex}}'
ZSH_HIGHLIGHT_STYLES[assign]='fg={{colors.error_container.dark.hex}}'
ZSH_HIGHLIGHT_STYLES[redirection]='fg={{colors.secondary.dark.hex}},bold'
ZSH_HIGHLIGHT_STYLES[comment]='fg={{colors.outline_variant.dark.hex}}'
ZSH_HIGHLIGHT_STYLES[named-fd]='none'
ZSH_HIGHLIGHT_STYLES[numeric-fd]='none'
ZSH_HIGHLIGHT_STYLES[arg0]='fg={{colors.primary.dark.hex}},bold'

# Brackets
ZSH_HIGHLIGHT_STYLES[bracket-error]='fg={{colors.error.dark.hex}},bold'
ZSH_HIGHLIGHT_STYLES[bracket-level-1]='fg={{colors.secondary.dark.hex}},bold'
ZSH_HIGHLIGHT_STYLES[bracket-level-2]='fg={{colors.primary.dark.hex}},bold'
ZSH_HIGHLIGHT_STYLES[bracket-level-3]='fg={{colors.tertiary.dark.hex}},bold'
ZSH_HIGHLIGHT_STYLES[bracket-level-4]='fg={{colors.error.dark.hex}},bold'
ZSH_HIGHLIGHT_STYLES[bracket-level-5]='fg={{colors.primary_container.dark.hex}},bold'
ZSH_HIGHLIGHT_STYLES[cursor-matchingbracket]='fg={{colors.on_surface_variant.default.hex}},bg={{colors.error_container.dark.hex}},bold'

# Root
ZSH_HIGHLIGHT_STYLES[root]='standout'

# Line
ZSH_HIGHLIGHT_STYLES[line]=''

# Autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg={{colors.outline_variant.dark.hex}}'