ble-face argument_error=fg=#1e1e28,bg=#f28fad
ble-face argument_option=fg=#89b4fa
ble-face auto_complete=fg=#89dceb,bg=#344d53
#bg=#dcd7ba
ble-face cmdinfo_cd_cdpath=fg=#89b4fa,bg=#eba0ac
ble-face command_alias=fg=#89b4fa
ble-face command_builtin=fg=#f28fad
ble-face command_builtin_dot=fg=#f28fad,bold
ble-face command_directory=fg=#a6e3a1,underline
ble-face command_file=fg=#89dceb
ble-face command_function=fg=#cba6f7
ble-face command_jobs=fg=#f28fad,bold
ble-face command_keyword=fg=#89b4fa
ble-face command_suffix=fg=#dcd7ba,bg=#a6e3a1
ble-face command_suffix_new=fg=#dcd7ba,bg=#f28fad
ble-face disabled=fg=#24273a
ble-face filename_block=fg=#dcd7ba,bg=#1e1e28,underline
ble-face filename_character=fg=#dcd7ba,bg=#1e1e28,underline
ble-face filename_directory=fg=#a6e3a1,underline
ble-face filename_directory_sticky=fg=#dcd7ba,bg=#89b4fa,underline
ble-face filename_executable=fg=#89dceb,underline
ble-face filename_link=fg=#89b4fa,underline
ble-face filename_ls_colors=underline
ble-face filename_orphan=fg=#1e1e28,bg=#f28fad,underline
ble-face filename_other=underline
ble-face filename_pipe=fg=#a6e3a1,bg=#1e1e28,underline
ble-face filename_setgid=fg=#1e1e28,bg=#ff9e64,underline
ble-face filename_setuid=fg=#1e1e28,bg=#f5c2e7,underline
ble-face filename_socket=fg=#89b4fa,bg=#1e1e28,underline
ble-face filename_url=fg=#89b4fa,underline
ble-face filename_warning=fg=#f28fad,underline
ble-face menu_complete_match=bold
ble-face menu_complete_selected=reverse
ble-face menu_desc_default=none
ble-face menu_desc_quote=ref:syntax_quoted
ble-face menu_desc_type=ref:syntax_delimiter
ble-face menu_filter_fixed=bold
ble-face menu_filter_input=fg=#1e1e28,bg=#f5c2e7
ble-face overwrite_mode=fg=#1e1e28,bg=#a6e3a1
ble-face prompt_status_line=fg=#dcd7ba,bg=#24273a
ble-face region=fg=#dcd7ba,bg=#ff9e64
ble-face region_insert=fg=#89dceb,bg=#dcd7ba
ble-face region_match=fg=#dcd7ba,bg=#f28fad
ble-face region_target=fg=#1e1e28,bg=#ff9e64
ble-face syntax_brace=fg=#a6e3a1,bold
ble-face syntax_command=fg=#ff9e64
ble-face syntax_comment=fg=#24273a
ble-face syntax_default=none
ble-face syntax_delimiter=bold
ble-face syntax_document=fg=#f5c2e7
ble-face syntax_document_begin=fg=#f5c2e7,bold
ble-face syntax_error=fg=#dcd7ba,bg=#f28fad
ble-face syntax_escape=fg=#89b4fa
ble-face syntax_expr=fg=#a6e3a1
ble-face syntax_function_name=fg=#cba6f7,bold
ble-face syntax_glob=fg=#ff9e64,bold
ble-face syntax_history_expansion=fg=#dcd7ba,bg=#f28fad
ble-face syntax_param_expansion=fg=#a6e3a1
ble-face syntax_quotation=fg=#89dceb,bold
ble-face syntax_quoted=fg=#89dceb
ble-face syntax_tilde=fg=#a6e3a1,bold
ble-face syntax_varname=fg=#ff9e64
ble-face varname_array=fg=#ff9e64,bold
ble-face varname_empty=fg=#cba6f7
ble-face varname_export=fg=#f28fad,bold
ble-face varname_expr=fg=#cba6f7,bold
ble-face varname_hash=fg=#f5c2e7,bold
ble-face varname_new=fg=#89b4fa
ble-face varname_number=fg=#f28fad
ble-face varname_readonly=fg=#f28fad
ble-face varname_transform=fg=#a6e3a1,bold
ble-face varname_unset=fg=#24273a
ble-face vbell=none
ble-face vbell_erase=none
ble-face vbell_flash=fg=#89dceb,reverse
