ble-face argument_error=fg=#191724,bg=#eb6f92
ble-face argument_option=fg=#9ccfd8
ble-face auto_complete=fg=#21202e,bg=#6a7094
ble-face cmdinfo_cd_cdpath=fg=#31748f,bg=#ebbcba
ble-face command_alias=fg=#9ccfd8
ble-face command_builtin=fg=#f6c177
ble-face command_builtin_dot=fg=#f6c177,bold
ble-face command_directory=fg=#9ccfd8,underline
ble-face command_file=fg=#31748f
ble-face command_function=fg=#c4a7e7
ble-face command_jobs=fg=#f6c177,bold
ble-face command_keyword=fg=#eb6f92
ble-face command_suffix=fg=#e0def4,bg=#31748f
ble-face command_suffix_new=fg=#e0def4,bg=#f6c177
ble-face disabled=fg=#59546d
ble-face filename_block=fg=#eb6f92,bg=#191724,underline
ble-face filename_character=fg=#eb6f92,bg=#191724,underline
ble-face filename_directory=fg=#31748f,underline
ble-face filename_directory_sticky=fg=#e0def4,bg=#191724,underline
ble-face filename_executable=fg=#f6c177,underline
ble-face filename_link=fg=#9ccfd8,underline
ble-face filename_ls_colors=underline
ble-face filename_orphan=fg=#191724,bg=#eb6f92,underline
ble-face filename_other=underline
ble-face filename_pipe=fg=#9ccfd8,bg=#191724,underline
ble-face filename_setgid=fg=#191724,bg=#ebbcba,underline
ble-face filename_setuid=fg=#191724,bg=#c4a7e7,underline
ble-face filename_socket=fg=#eb6f92,bg=#191724,underline
ble-face filename_url=fg=#eb6f92,underline
ble-face filename_warning=fg=#eb6f92,underline
ble-face menu_complete_match=bold
ble-face menu_complete_selected=reverse
ble-face menu_desc_default=none
ble-face menu_desc_quote=ref:syntax_quoted
ble-face menu_desc_type=ref:syntax_delimiter
ble-face menu_filter_fixed=bold
ble-face menu_filter_input=fg=#191724,bg=#f6c177
ble-face overwrite_mode=fg=#191724,bg=#9ccfd8
ble-face prompt_status_line=fg=#e0def4,bg=#191724
ble-face region=fg=#ebbcba,bg=#31748f
ble-face region_insert=fg=#9ccfd8,bg=#e0def4
ble-face region_match=fg=#e0def4,bg=#eb6f92
ble-face region_target=fg=#191724,bg=#f6c177
ble-face syntax_brace=fg=#31748f,bold
ble-face syntax_command=fg=#eb6f92
ble-face syntax_comment=fg=#59546d
ble-face syntax_default=none
ble-face syntax_delimiter=bold
ble-face syntax_document=fg=#c4a7e7
ble-face syntax_document_begin=fg=#c4a7e7,bold
ble-face syntax_error=fg=#e0def4,bg=#eb6f92
ble-face syntax_escape=fg=#ebbcba
ble-face syntax_expr=fg=#31748f
ble-face syntax_function_name=fg=#c4a7e7,bold
ble-face syntax_glob=fg=#f6c177,bold
ble-face syntax_history_expansion=fg=#e0def4,bg=#eb6f92
ble-face syntax_param_expansion=fg=#9ccfd8
ble-face syntax_quotation=fg=#9ccfd8,bold
ble-face syntax_quoted=fg=#9ccfd8
ble-face syntax_tilde=fg=#31748f,bold
ble-face syntax_varname=fg=#f6c177
ble-face varname_array=fg=#f6c177,bold
ble-face varname_empty=fg=#c4a7e7
ble-face varname_export=fg=#f6c177,bold
ble-face varname_expr=fg=#c4a7e7,bold
ble-face varname_hash=fg=#c4a7e7,bold
ble-face varname_new=fg=#ebbcba
ble-face varname_number=fg=#f6c177
ble-face varname_readonly=fg=#f6c177
ble-face varname_transform=fg=#9ccfd8,bold
ble-face varname_unset=fg=#59546d
ble-face vbell=none
ble-face vbell_erase=none
ble-face vbell_flash=fg=#eb6f92,reverse
