-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/
hl.config({ autogenerated = false })

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")
------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
	output = "",
	mode = "preferred",
	position = "auto",
	scale = "auto",
})
require("monitors")

-----------------------
--- Local variables ###
-----------------------
local mod = "SUPER"
local terminal = "prime-run ghostty"
local fileManager = "prime-run nemo"
local menu = "rofi -show run"
local colors = require("dms.matugen_colors")

-- Convert "#RRGGBB" to "rgb(RRGGBB)" for Hyprland
local function rgb(hex)
	return "rgb(" .. hex:sub(2) .. ")"
end

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

-- hl.env("XCURSOR_SIZE", "24")
require("modules.environment")

-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

hl.config({
	-- ecosystem = {
	--   enforce_permissions = true,
	-- },
	input = {
		kb_layout = "us",
		-- # numlock_by_default = true
		repeat_delay = 150,
		repeat_rate = 50,
		kb_variant = "",
		kb_model = "",
		kb_options = "caps:swapescape",
		kb_rules = "",

		follow_mouse = 2,
		-- # emulate_discrete_scroll = 1
		-- # mouse_refocus = 0
		-- # off_window_axis_events = 2

		sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

		touchpad = {
			-- # disable_while_typing = true
			natural_scroll = true,
			-- # clickfinger_behavior = true
			middle_button_emulation = true,
			disable_while_typing = false,
			-- # scroll_factor = 0.5
		},
	},
	group = {
		col = {
			-- border_active = rgb(colors.primary) .. " " .. rgb(colors.outline) .. " 45deg",
			-- border_locked_active = rgb(colors.error) .. " " .. rgb(colors.outline) .. " 45deg",
			border_inactive = "rgba(4f4f4faa)",
		},
		groupbar = {
			font_size = 11,
			text_color = "rgba(AEE9D1aa)",
			font_weight_active = "bold",
			col = {
				-- active = rgb(colors.primary) .. " " .. rgb(colors.outline) .. " 90deg",
				-- locked_active = rgb(colors.error) .. " " .. rgb(colors.outline) .. " 90deg",
				inactive = "rgba(707070ff)",
				locked_inactive = "rgba(707070ff)",
			},
		},
	},
	general = {
		gaps_in = 2,
		gaps_out = 2,
		border_size = 2,
		col = {
			-- active_border = rgb(colors.primary) .. " " .. rgb(colors.outline) .. " 45deg",
			inactive_border = "rgba(707070ff)",
		},
		resize_on_border = true,
		extend_border_grab_area = 20,
		allow_tearing = false,
	},

	decoration = {
		rounding = 4,
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		shadow = {
			enabled = false,
			range = 30,
			render_power = 5,
			offset = "0 5",
			color = "rgba(00000070)",
		},
		blur = {
			enabled = false,
			size = 4,
			passes = 6,
			vibrancy = 0.1696,
		},
	},

	-- animations = {
	-- 	enabled = true,
	-- 	bezier = {
	-- 		{ name = "easeOutQuint", x0 = 0.23, y0 = 1, x1 = 0.32, y1 = 1 },
	-- 		{ name = "easeInOutCubic", x0 = 0.65, y0 = 0.05, x1 = 0.36, y1 = 1 },
	-- 		{ name = "linear", x0 = 0, y0 = 0, x1 = 1, y1 = 1 },
	-- 		{ name = "almostLinear", x0 = 0.5, y0 = 0.5, x1 = 0.75, y1 = 1.0 },
	-- 		{ name = "quick", x0 = 0.15, y0 = 0, x1 = 0.1, y1 = 1 },
	-- 	},
	-- 	animation = {
	-- 		{ name = "windowsIn", enabled = 1, speed = 3, curve = "default" },
	-- 		{ name = "windowsOut", enabled = 1, speed = 3, curve = "default" },
	-- 		{ name = "windowsMove", enabled = 1, speed = 4, curve = "default" },
	-- 		{ name = "fade", enabled = 1, speed = 3, curve = "default" },
	-- 		{ name = "border", enabled = 1, speed = 3, curve = "default" },
	-- 		{ name = "workspaces", enabled = 1, speed = 0.97, curve = "almostLinear", style = "fade" },
	-- 		{ name = "workspacesIn", enabled = 1, speed = 0.605, curve = "almostLinear", style = "slidevert" },
	-- 		{ name = "workspacesOut", enabled = 1, speed = 0.97, curve = "almostLinear", style = "slidevert" },
	-- 	},
	-- },

	dwindle = {
		preserve_split = true,
	},

	master = {
		new_status = "master",
	},

	scrolling = {
		fullscreen_on_one_column = true,
		focus_fit_method = 1,
		follow_focus = true,
	},

	xwayland = {
		force_zero_scaling = true,
	},

	misc = {
		force_default_wallpaper = 0,
		disable_hyprland_logo = true,
		focus_on_activate = true,
		disable_splash_rendering = true,
		vrr = 1,
		mouse_move_enables_dpms = true,
		key_press_enables_dpms = true,
		enable_swallow = false,
		swallow_regex = "(foot|kitty|allacritty|Alacritty|ghostty)",
		on_focus_under_fullscreen = 1,
		exit_window_retains_fullscreen = false,
		allow_session_lock_restore = 1,
		background_color = "rgba(0,0,0,0)",
		session_lock_xray = true,
		initial_workspace_tracking = 2,
	},

	cursor = {
		no_hardware_cursors = 1,
		zoom_factor = 1,
		zoom_rigid = true,
		inactive_timeout = 0.3,
		hide_on_key_press = true,
		no_warps = true,
		zoom_disable_aa = false,
	},

	binds = {
		scroll_event_delay = 0,
	},

	debug = {
		vfr = true,
	},
	-- plugin = {
	-- 	scrolloverview = {
	-- 		gesture_distance = 300, -- how far is the "max" for the gesture
	-- 		scale = 0.5, -- preferred overview scale
	-- 		workspace_gap = 100,
	-- 		layout = "vertical", -- vertical or horizontal
	-- 		wallpaper = 0, -- 0: global only, 1: per-workspace only, 2: both
	-- 		blur = false, -- blur only the main overview wallpaper
	--
	-- 		shadow = {
	-- 			enabled = false,
	-- 			range = 50,
	-- 		},
	-- 	},
	-- },
})
require("dms.colors")
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 0.605, bezier = "default", style = "slidevert" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 0.97, bezier = "default", style = "slidevert" })

hl.animation({ leaf = "windowsIn", enabled = true, speed = 1.5, bezier = "default" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.5, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 2.5, bezier = "default", style = "fade" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 2, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 1.5, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 1.5, bezier = "default" })

-- window rules
hl.window_rule({ match = { class = "^(org\\.wezfurlong\\.wezterm)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.)" }, rounding = 12 })
hl.window_rule({ match = { class = "^(gnome-control-center)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.pulseaudio\\.pavucontrol)$" }, float = true })
hl.window_rule({ match = { class = "^(org\\.kde\\.kcalc)$" }, float = true })
hl.window_rule({ match = { class = "^(org\\.opengamingcollective\\.rog-control-center)$" }, float = true })
hl.window_rule({ match = { class = "^(nm-connection-editor)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(pcmanfm-qt)$" }, float = true })
hl.window_rule({ match = { class = "^(com\\.github\\.hluk\\.copyq)$" }, float = true })
hl.window_rule({ match = { class = "^(gnome-calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(galculator)$" }, float = true })
hl.window_rule({ match = { class = "^(blueman-manager)$" }, float = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Nautilus)$" }, float = true })
hl.window_rule({ match = { class = "^(nemo)$" }, float = true })
hl.window_rule({ match = { class = "^(org\\.kde\\.dolphin)$" }, float = true })
hl.window_rule({ match = { class = "^(Thunar)$" }, float = true })
hl.window_rule({ match = { class = "^(xdg-desktop-portal)$" }, float = true })
hl.window_rule({
	match = { class = "^(steam)$", title = "^(notificationtoasts)" },
	no_initial_focus = true,
	pin = true,
})
hl.window_rule({
	match = { class = "^(firefox)$", title = "^(Picture-in-Picture)$" },
	float = true,
})
hl.window_rule({
	match = { class = "^(app\\.zen_browser\\.zen)$", title = "^(Picture-in-Picture)$" },
	float = true,
})
hl.window_rule({ match = { class = "^(zoom)$" }, float = true })
hl.layer_rule({ match = { namespace = "^(quickshell)$" }, no_anim = true })
hl.layer_rule({ match = { namespace = "^dms:.*" }, no_anim = true })

require("modules.gestures")

-- === Application Launchers ===
require("modules.keybinds")

-- === Move to Workspacesets ===
require("modules.submaps")

-- === Lid switch ===
-- hl.bind("switch:off:Lid Switch", hl.exec_cmd("systemctl suspend"))
-- hl.bind("switch:on:Lid Switch", hl.exec_cmd("hyprctl dispatch dpms on"))

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")

-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
hl.on("hyprland.start", function()
	-- hl.exec_cmd(terminal)
	-- hl.exec_cmd("nm-applet")
	-- hl.exec_cmd("waybar & hyprpaper & firefox")
	-- # exec-once = hyprpaper &
	-- # exec-once = killall dunst && dunst &
	-- # exec-once = lxqt-policykit-agent &
	-- # exec-once = wl-paste --type text --watch cliphist store
	-- # exec-once = wl-paste --type image --watch cliphist store
	-- # exec-once = waybar & hyprpaper & firefox
	-- # exec-once = nm-applet &
	-- # exec-once = blueman-applet &
	-- # exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
	-- # exec-once = dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS
	-- # exec-once = /usr/lib/mate-polkit/polkit-mate-authentication-agent-1
	-- # exec-once = bash ~/protal.sh
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
	hl.exec_cmd("hyprctl setcursor cz-Hickson-black 24")
	hl.exec_cmd("xrdb ~/.Xresources")
	-- # exec-once = hyprctl setcursor breeze_cursors 24
	-- # exec-once = killall hypridle & hypridle
	hl.exec_cmd("bash -c 'wl-paste --watch cliphist store &'")
	hl.exec_cmd("hyprpm reload -n")
	hl.exec_cmd("dms run")
	hl.exec_cmd("hyprshell run")
	hl.exec_cmd("pcmanfm-qt --desktop")
	-- # # exec-once = systemctl --user start hyprpolkitagent
	hl.exec_cmd("hyprsunset")
	-- # # exec-once = snixembed
	hl.exec_cmd("elephant")
	hl.exec_cmd("copyq --start-server")
	hl.exec_cmd("flameshot")
	hl.exec_cmd("walker --gapplication-service")
	hl.exec_cmd("wayscriber --daemon")
	hl.exec_cmd("kwalletd6")
	hl.exec_cmd("prime-run ghostty", { workspace = "1 silent" })
	hl.exec_cmd("prime-run kitty", { workspace = "special:magic silent" })
	hl.exec_cmd("prime-run zen", { workspace = "2 silent" })
	-- # exec-once = [workspace 5 silent] ~/AppImages/squashfs-root/AppRun

	-- # exec-once = [workspace 5 silent] sleep 1 && prime-run helium-browser --ozone-platform=x11
	-- hl.exec_cmd("prime-run helium-browser --ozone-platform=wayland --use-gl=egl", { workspace = "5 silent" })
	hl.exec_cmd("prime-run helium-browser --ozone-platform=x11", { workspace = "5 silent" })
	hl.exec_cmd("prime-run librewolf", { workspace = "6 silent" })
	-- # for dolphin
	-- # disabled cause the tray gets broken
	-- # exec-once = XDG_MENU_PREFIX=plasma- kbuildsycoca6 --noincremental
	-- # exec-once = kded6 &
end)

----------------------
---- WINDOW RULES ----
----------------------
hl.workspace_rule({ workspace = "2", layout = "scrolling" })
-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
hl.workspace_rule({ workspace = "f[1]", gaps_out = 0, gaps_in = 0 })
hl.window_rule({
	name = "no-gaps-wtv1",
	match = { float = false, workspace = "w[tv1]" },
	border_size = 0,
	rounding = 0,
})
hl.window_rule({
	name = "no-gaps-f1",
	match = { float = false, workspace = "f[1]" },
	border_size = 0,
	rounding = 0,
})

-- hl.workspace({ rules = { "layout:scrolling" }, selector = "2" })
-- hl.workspace({ rules = { "layout:scrolling" }, selector = "5" })
--
-- hl.windowrule({ border_size = 0, match = { float = false, workspace = "w[tv1]" } })
-- hl.windowrule({ rounding = 0, match = { float = false, workspace = "w[tv1]" } })
-- hl.windowrule({ border_size = 0, match = { float = false, workspace = "f[1]" } })
-- hl.windowrule({ rounding = 0, match = { float = false, workspace = "f[1]" } })
--
-- hl.windowrule({ tile = true, match = { class = "^(org\\.wezfurlong\\.wezterm)$" } })
-- hl.windowrule({ rounding = 12, match = { class = "^(org\\.gnome\\.)" } })
-- hl.windowrule({ border_size = 0, match = { class = "^(org\\.gnome\\.)" } })
--
-- hl.windowrule({ tile = true, match = { class = "^(gnome-control-center)$" } })
-- hl.windowrule({ tile = true, match = { class = "^(pavucontrol)$" } })
-- hl.windowrule({ tile = true, match = { class = "^(nm-connection-editor)$" } })
--
-- hl.windowrule({ float = true, match = { class = "^(gnome-calculator)$" } })
-- hl.windowrule({ float = true, match = { class = "^(galculator)$" } })
-- hl.windowrule({ float = true, match = { class = "^(blueman-manager)$" } })
-- hl.windowrule({ float = true, match = { class = "^(xdg-desktop-portal)$" } })
--
-- hl.windowrule({ border_size = 0, match = { class = "^(org\\.wezfurlong\\.wezterm)$", float = false } })
-- hl.windowrule({ border_size = 0, match = { class = "^(Alacritty)$", float = false } })
-- hl.windowrule({ border_size = 0, match = { class = "^(com\\.mitchellh\\.ghostty)$", float = false } })
-- hl.windowrule({ border_size = 0, match = { class = "^(kitty)$", float = false } })
--
-- hl.windowrule({ float = true, match = { class = "^(app\\.zen_browser\\.zen)$", title = "^(Picture-in-Picture)$" } })
-- hl.windowrule({ float = true, match = { class = "^(librewolf)$", title = "^(Picture-in-Picture)$" } })
-- hl.windowrule({ float = true, match = { class = "^(helium)$", title = "^(Picture-in-Picture)$" } })
-- hl.windowrule({ float = true, match = { class = "^(zoom)$" } })

-- hl.windowrule({
-- 	name = "flameshot",
-- 	no_anim = true,
-- 	pin = false,
-- 	float = true,
-- 	fullscreen_state = "2 0",
-- 	move = "0 0",
-- 	content = "photo",
-- 	match = {
-- 		class = "flameshot",
-- 		title = "flameshot",
-- 	},
-- })

-- windowrule for transparent tag removed - tagwindow broken in 0.56, using setprop instead

-- hl.windowrule({ float = true, match = { class = "^(com\\.github\\.hluk\\.copyq)$" } })
-- hl.windowrule({ size = "400 375", match = { class = "^(com\\.github\\.hluk\\.copyq)$" } })
-- hl.windowrule({ move = "(cursor_x-(window_w*0)) (cursor_y-(window_h*0))", match = { class = "^(com\\.github\\.hluk\\.copyq)$" } })
--
-- hl.windowrule({ float = true, match = { class = "^(io\\.github\\.Qalculate\\.qalculate-qt)$" } })
-- hl.windowrule({ size = "500 500", match = { class = "^(io\\.github\\.Qalculate\\.qalculate-qt)$" } })
--
-- hl.windowrule({
-- 	name = "fix-xwayland-drags",
-- 	match = {
-- 		class = "^$",
-- 		title = "^$",
-- 		xwayland = true,
-- 		float = true,
-- 		fullscreen = false,
-- 		pin = false,
-- 	},
-- 	no_focus = true,
-- })

-- hl.layerrule({ no_anim = true, match = { namespace = "^(quickshell)$" } })
-- hl.layerrule({ no_anim = true, match = { namespace = "^(desktop)$" } })

hl.device({
	name = "epic-mouse-v1",
	sensitivity = 0.5,
})

-------------------
---- PLUGINS ------
-------------------

-- hl.plugin("dynamic-cursors", {
-- 	enabled = false,
-- 	mode = "none",
-- 	threshold = 2,
-- 	rotate = {
-- 		length = 20,
-- 		offset = 0.0,
-- 	},
-- 	tilt = {
-- 		limit = 5000,
-- 		-- function = "negative_quadratic",
-- 		window = 100,
-- 	},
-- 	stretch = {
-- 		limit = 3000,
-- 		function = "quadratic",
-- 		window = 100,
-- 	},
-- 	shake = {
-- 		enabled = true,
-- 		nearest = true,
-- 		threshold = 5.785,
-- 		base = 3.0,
-- 		speed = 1.0,
-- 		influence = 0.0,
-- 		limit = 0.0,
-- 		timeout = 2000,
-- 		effects = false,
-- 		ipc = false,
-- 	},
-- 	hyprcursor = {
-- 		nearest = true,
-- 		enabled = true,
-- 		resolution = -1,
-- 		fallback = "clientside",
-- 	},
-- })

-- hl.plugin("overview", {
-- 	overrideGaps = false,
-- 	gapsIn = 10,
-- 	gapsOut = 30,
-- 	panelHeight = 300,
-- 	reservedArea = 32,
-- 	workspaceActiveBorder = "rgba(99999999)",
-- 	workspaceInactiveBorder = "rgba(55555599)",
-- 	drawActiveWorkspace = false,
-- 	showOvelayLayers = true,
-- 	hideRealLayers = true,
-- 	affectStrut = false,
-- 	panelBorderWidth = 0,
-- 	panelBorderColor = "rgba(707070cc)",
-- 	panelColor = "rgba(10101044)",
-- })
if hl.plugin.hyprglass then
    local hg = hl.plugin.hyprglass

    hg.config({
        default_theme = "dark",
        default_preset = "clear",
        tint_color = 0x8899aa22,

        brightness = 0.9,
        dark = { brightness = 0.82 },
        light = { adaptive_boost = 0.5 },

        layers = { enabled = 1 },
    })

    -- Layer surfaces: each call whitelists the namespace and configures it
    -- hg.layer("waybar", { preset = "subtle", mask_threshold = 0.05 })
    -- hg.layer("swaync")
    -- hg.layer("quickshell:bezel", { preset = "ui", mask_threshold = 0.3 })
    -- hg.layer("debug-panel", { exclude = true })

    -- Presets
    hg.preset("clear", {
        glass_opacity = 0.8,
        blur_strength = 1.5,
        dark = { brightness = 0.7 },
        light = { brightness = 1.2 },
    })

    hg.preset("contrasted", {
        inherits = "high_contrast",
        contrast = 1.2,
        adaptive_dim = 1.5,
        dark = { tint_color = 0x02142aa9 },
    })
end
-- Switch to a submap called `resize`.
hl.bind("SUPER + R", function ()
                                hl.dispatch(hl.dsp.submap("resize"))
                                hl.exec_cmd("notify-send 'Resize submap Started'") end)

-- Start a submap called "resize".
hl.define_submap("resize", function()
    -- hl.exec_cmd("notify-send 'Resize submap started'")

    -- Set repeating binds for resizing the active window.
    hl.bind("right", hl.dsp.window.resize({ x = 10, y = 0, relative = true}), { repeating = true })
    hl.bind("left", hl.dsp.window.resize({ x = -10, y = 0, relative = true}), { repeating = true })
    hl.bind("up", hl.dsp.window.resize({ x = 0, y = 10, relative = true}), { repeating = true })
    hl.bind("down", hl.dsp.window.resize({ x = 0, y = -10, relative = true}), { repeating = true })

    -- Use `reset` to go back to the global submap
    hl.bind("escape", function () hl.dispatch(hl.dsp.submap("reset"))
                                  hl.exec_cmd("notify-send 'Resize submap reset'") end)

end)
-- require("hyprland-gui")
