ble-face argument_error=fg=#1a1b26,bg=#f7768e
ble-face argument_option=fg=#7aa2f7
ble-face auto_complete=fg=#3e487f,bg=#2f96b8 #bg=#2f96b8
ble-face cmdinfo_cd_cdpath=fg=#7aa2f7,bg=#f7768e
ble-face command_alias=fg=#7aa2f7
ble-face command_builtin=fg=#f7768e
ble-face command_builtin_dot=fg=#f7768e,bold
ble-face command_directory=fg=#9ece6a,underline
ble-face command_file=fg=#7dcfff
ble-face command_function=fg=#bb9af7
ble-face command_jobs=fg=#f7768e,bold
ble-face command_keyword=fg=#7aa2f7
ble-face command_suffix=fg=#2f96b8,bg=#9ece6a
ble-face command_suffix_new=fg=#2f96b8,bg=#f7768e
ble-face disabled=fg=#3b4261
ble-face filename_block=fg=#2f96b8,bg=#1a1b26,underline
ble-face filename_character=fg=#2f96b8,bg=#1a1b26,underline
ble-face filename_directory=fg=#9ece6a,underline
ble-face filename_directory_sticky=fg=#2f96b8,bg=#7aa2f7,underline
ble-face filename_executable=fg=#7dcfff,underline
ble-face filename_link=fg=#7aa2f7,underline
ble-face filename_ls_colors=underline
ble-face filename_orphan=fg=#1a1b26,bg=#f7768e,underline
ble-face filename_other=underline
ble-face filename_pipe=fg=#9ece6a,bg=#1a1b26,underline
ble-face filename_setgid=fg=#1a1b26,bg=#ff9e64,underline
ble-face filename_setuid=fg=#1a1b26,bg=#bb9af7,underline
ble-face filename_socket=fg=#7aa2f7,bg=#1a1b26,underline
ble-face filename_url=fg=#7aa2f7,underline
ble-face filename_warning=fg=#f7768e,underline
ble-face menu_complete_match=bold
ble-face menu_complete_selected=reverse
ble-face menu_desc_default=none
ble-face menu_desc_quote=ref:syntax_quoted
ble-face menu_desc_type=ref:syntax_delimiter
ble-face menu_filter_fixed=bold
ble-face menu_filter_input=fg=#1a1b26,bg=#bb9af7
ble-face overwrite_mode=fg=#1a1b26,bg=#9ece6a
ble-face prompt_status_line=fg=#2f96b8,bg=#3b4261
ble-face region=fg=#2f96b8,bg=#ff9e64
ble-face region_insert=fg=#7dcfff,bg=#2f96b8
ble-face region_match=fg=#2f96b8,bg=#f7768e
ble-face region_target=fg=#1a1b26,bg=#ff9e64
ble-face syntax_brace=fg=#9ece6a,bold
ble-face syntax_command=fg=#ff9e64
ble-face syntax_comment=fg=#3b4261
ble-face syntax_default=none
ble-face syntax_delimiter=bold
ble-face syntax_document=fg=#bb9af7
ble-face syntax_document_begin=fg=#bb9af7,bold
ble-face syntax_error=fg=#2f96b8,bg=#f7768e
ble-face syntax_escape=fg=#7aa2f7
ble-face syntax_expr=fg=#9ece6a
ble-face syntax_function_name=fg=#bb9af7,bold
ble-face syntax_glob=fg=#ff9e64,bold
ble-face syntax_history_expansion=fg=#2f96b8,bg=#f7768e
ble-face syntax_param_expansion=fg=#9ece6a
ble-face syntax_quotation=fg=#7dcfff,bold
ble-face syntax_quoted=fg=#7dcfff
ble-face syntax_tilde=fg=#9ece6a,bold
ble-face syntax_varname=fg=#ff9e64
ble-face varname_array=fg=#ff9e64,bold
ble-face varname_empty=fg=#bb9af7
ble-face varname_export=fg=#f7768e,bold
ble-face varname_expr=fg=#bb9af7,bold
ble-face varname_hash=fg=#bb9af7,bold
ble-face varname_new=fg=#7aa2f7
ble-face varname_number=fg=#f7768e
ble-face varname_readonly=fg=#f7768e
ble-face varname_transform=fg=#9ece6a,bold
ble-face varname_unset=fg=#3b4261
ble-face vbell=none
ble-face vbell_erase=none
ble-face vbell_flash=fg=#7dcfff,reverse
